### ISSUE TITLE
Delete My Script

### ISSUE THREAD

**Issue by DominusTrax** [mkswlorn/My-Repo#1]
You've recently added my script to this labeled "**Eclipsis Loader**." This is my first friendly notification telling you to remove this. You can either add a README.me and provide credits for my script or you can remove it. You have 2 business days to respond.

Original Repo: [https://github.com/DominusTrax/Eclipsis-Loader](https://github.com/DominusTrax/Eclipsis-Loader)

**Comment by mkswlorn** [comment]
Sorry i accidently added your repo. Fixed my mistake

**Comment by DominusTrax** [comment]
It's still there.. either give me credits or delete the script its self.
